### ISSUE TITLE
failing to build

### ISSUE THREAD

**Issue by tkrtz** [raikm/homepanorama#12]
I would like to know, how to use this dashboard. But if try to build it, I'm getting an `ERR! code 1` with the log:
```0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.5.1/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'run',
0 verbose cli   'build'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.1
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/thomaskretz/Documents/GitHub/homepanorama/.npm$
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/thomaskretz/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 verbose npm-session 09b0c06e5f7aba18
20 timing npm:load Completed in 14ms
21 timing command:run-script Completed in 24919ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/n$
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1063:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/chil$
23 verbose pkgid homeapp@0.1.0
24 verbose cwd /Users/thomaskretz/Documents/GitHub/homepanorama
25 verbose Darwin 20.2.0
26 verbose argv "/usr/local/Cellar/node/15.5.1/bin/node" "/usr/local/bin/npm" "$
27 verbose node v15.5.1
28 verbose npm  v7.3.0
29 error code 1
30 error path /Users/thomaskretz/Documents/GitHub/homepanorama
31 error command failed
32 error command sh -c vue-cli-service build
33 verbose exit 1```

**Comment by levidavis** [comment]
I to have the exact same problem

**Comment by raikm** [comment]
First of all, try to run it without electron and let me know if you have problems as well.

I guess it is because of the loading url "http://homeapp.com:8080/" what is not available in your network environment. You can change that in the background.js file in line 28 to e.g. http://localhost:8080/.

The reason for my setup is to have a verified URL for the Google API for whitelisting for fetching calendar data.

**Comment by tkrtz** [comment]
Before running it with electron, I already tried the web-version. Same result. Editing line 28 did not change the outcome.

**Comment by raikm** [comment]
Can you provide the outcome when you run 

```
npm run serve
```

**Comment by tkrtz** [comment]
Sure, it's
``` WARNING  Compiled with 1 warnings                                   12:10:20 PM

 warning  in ./src/pages/PlantsPage/index.vue?vue&type=script&lang=js&

Critical dependency: the request of a dependency is an expression


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.1.108:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.


```

**Comment by raikm** [comment]
hmm I am not familiar with this warning but as I can see the app is running and you can reach it thru http://localhost:8080/  or http://192.168.1.108:8080/ in your browser.

**Comment by tkrtz** [comment]
As I've told you, I only get a blank white screen. Doesn't matter which browser I use.
But all of them say `We're sorry but homeapp doesn't work properly without JavaScript enabled. Please enable it to continue.` in the `<body>` section. I've checked my browser settings multiple times and do have it enabled.

**Comment by raikm** [comment]
Hi, did you check your console in the browser for more information? 

Maybe something is not up to date (nodejs?) or disabled.

Another idea I just had: since you have no external apis configured like aftership, google (config.json) I would suggest do comment all axios request to avoid failing get/post queries since they are anyways not working. 

I just made a clean pull on another device today and had no problems to make the software running.

**Comment by tkrtz** [comment]
Hey, been busy with other things lately and won't test it out in the near future. I will still follow for updates. Keep up the great work!
